### ISSUE TITLE
Dataset - ground truth

### ISSUE THREAD

**Issue by nashid** [NiSE-Virginia-Tech/ying-ICPC-2022#7]
Hi! thanks for your fantastic work.

I would like to whether you plan to share the ground truth dataset with the <insecure, secure> code? 

-  I—insecure code with certain security-API misuse, and
- S—the secure counterpart showing the correct API usage

Would be great if you please point me where you shared the insecure and secure code pair. Looking forward to your response.

**Comment by NEUZhangy** [comment]
Hi, 
   May I know which part of the ground truth? we used the third-party data set in the detection, you may [refer here](https://github.com/NEUZhangy/ApacheCryptoAPI-Bench/tree/2b680d2ece74da5372333ad4c41ec3dd8b7c0504) 

https://github.com/NiSE-Virginia-Tech/ying-ICPC-2022/blob/main/dataset/patterns%20-%20ICPC.csv

**Comment by mengna152173** [comment]
Hi Ying,

I think the person talks about the <insecure, secure> code pairs used for pattern inference.

Cheers,
Na
________________________________
